### ISSUE TITLE
please slove this error

### ISSUE THREAD

**Issue by 23bca283** [vtcbca/internal-exam-23BCA282#3]
here i am attaching a photo.
![image](https://github.com/user-attachments/assets/10e08677-4690-49eb-bad0-394950b8cf2d)

**Comment by 23bca274** [comment]
You've to write " f.writelines " instead of " f.writeline " coz this will only used to print one line and " f.writelines " prints more than one line.

This may help you !

**Comment by 23BCA281** [comment]
write " f.writelines " to execute more than one line

**Comment by 23BCA282** [comment]
> You've to write " f.writelines " instead of " f.writeline " coz this will only used to print one line and " f.writelines " prints more than one line.
> 
> This may help you !

Thanks for your suggetions it was very helpful.
