### ISSUE TITLE
commit issue

### ISSUE THREAD

**Issue by 23BCA282** [vtcbca/internal-exam-23BCA282#4]
![image](https://github.com/user-attachments/assets/2a3a2e70-e424-4e29-b70d-7a1805ef46a5)
how i can save file in sqlite 3. **.commit is not working**

**Comment by 23bca274** [comment]
You tried commit command more than one time after wrong commit command such as " .commit " and ".commit ; " that's why you got the error of " no transaction is alive " .

Create table again and save the data with right commit command [ commit ; ]

**Comment by 23BCA281** [comment]
Here you have used commit command multiple times due to which sqlite3 got confused so you should create the table again in sqlite3 and save by using  COMMIT;
> ![image](https://github.com/user-attachments/assets/2a3a2e70-e424-4e29-b70d-7a1805ef46a5)
> how i can save file in sqlite 3. **.commit is not working**

**Comment by 23BCA282** [comment]
query resolved
